config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

  resources :games
  resources :leaderboards, only: :index
end

app/models/concerns/elo_ranking.rb
require 'active_support/concern'

module EloRanking
  extend ActiveSupport::Concern

  WIN_FEE = 0.3
  LOSER_FEE = 0.7
  FIRST_GAME_FEE = 10

  module ClassMethods
    def calculate_elo(game)
      @game = game
      @players = game.players
      @winner = @players[:winner]
      @loser = @players[:loser]
      set_winner_elo
      set_loser_elo
    end

    private

    def set_winner_elo
      @winner.update_column(:elo, (@winner.elo + winner_fee).round(1))
    end

    def set_loser_elo
      @loser.update_column(:elo, @loser.elo - loser_fee)
    end

    def winner_fee
      elo = @loser.elo
      winner_elo = elo * WIN_FEE
      return winner_elo if winner_elo > 0
      FIRST_GAME_FEE
    end

    def loser_fee
      elo = @loser.elo
      loser_elo = elo - (elo * LOSER_FEE)
      return loser_elo if loser_elo > 0
      0
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :opponent, class_name: 'User'

  validates_presence_of :date_played,
    :opponent_id,
    :user_score,
    :opponent_score

  validate :score_is_winnable?

  validate :valid_score?

  before_create :won_result

  def players
    if user_score > opponent_score
      { winner: user, loser: opponent }
    else
      { winner: opponent, loser: user }
    end
  end

  private

  def won_result
   self.won = true if user_score > opponent_score
  end

  def score_is_winnable?
    return true if user_score == 21 || opponent_score == 21
    errors.add(:score, "A score must to be 21")
  end

  def valid_score?
    return false if user_score.blank? || opponent_score.blank?
    return true if (user_score - opponent_score).abs >= 2
    errors.add(:score, "The difference of point must to be 2")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
  include EloRanking

  has_many :games

  scope :opponents, -> (user) {
    User.where.not(id: user)
  }

  scope :for_ranking, ->{
    includes(:games).order(elo: :desc)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      calculate_elo
      redirect_to games_path
    else
      render :new
    end
  end

  def index
    @games = Game.all
  end

  private

  def game_params
    params.require(:game).permit(
      :date_played,
      :opponent_id,
      :user_score,
      :opponent_score,
      :user_id
    )
  end

  def calculate_elo
    User.calculate_elo(@game)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def index
    @users = User.for_ranking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def opponents
    User.opponents(current_user)
  end

  def score(game)
    "#{ game.user_score } - #{ game.opponent_score }"
  end

  def result(game)
    return "W" if game.won?
    "L"
  end
end

app/views/games/_errors.html.erb
<div>
  <h5>Verify the next errors list </h5>
  <ul>
    <% byebug %>
    <% @game.errors.full_messages.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
</div>

app/views/games/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Opponent</th>
      <th scope="col">Score</th>
      <th scope="col">Result</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
    <tr>
      <td><%= game.date_played %></td>
      <th><%= game.opponent.email %></th>
      <td><%= score(game) %></td>
      <td><%= result(game) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'New game', new_game_path %>
</div>

app/views/games/new.html.erb
<%= form_for @game, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
 <%= render partial: 'errors' if @game.errors.present? %>

 <%= f.hidden_field :user_id, value: current_user.id %>

 <div class="form-group">
   <%= f.label :date_played, nil, class: 'control-label' %>
   <%= f.date_field :date_played, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :opponent_id, 'Opponent' %>
   <%= f.collection_select :opponent_id, opponents, :id, :email, {include_blank: true}, { class: "form-control" } %>
 </div>
 <div class="form-group">
   <%= f.label :user_score, 'Your score' %>
   <%= f.number_field :user_score, class: "form-control" %>
 </div>

 <div class="form-group">
   <%= f.label :opponent_score, 'Opponent score' %>
   <%= f.number_field :opponent_score, class: "form-control" %>
 </div>

  <%= f.submit "Save" %>
<% end %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="/">Pingpong</a>-->
<%= link_to 'Leadboard', leaderboards_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', leaderboards_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', games_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboards/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Email</th>
      <th scope="col">Score</th>
      <th scope="col">Games Played</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <th><%= user.email %></th>
      <td><%= user.elo %></td>
      <td><%= user.games.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>